### ISSUE TITLE
Failing to run bazel build "..." on Mac OS

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/nx-bazel-example#8]
When building getting the following output on terminal:

➜  nx-bazel-example git:(master) bazel build "..."
INFO: Analysed 27 targets (9 packages loaded).
INFO: Found 27 targets...
INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(arenastring.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(atomicops_internals_x86_msvc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(io_win32.o) has no symbols
INFO: From Compiling external/com_google_protobuf/src/google/protobuf/compiler/js/embed.cc [for host]:
external/com_google_protobuf/src/google/protobuf/compiler/js/embed.cc:37:12: warning: unused variable 'output_file' [-Wunused-const-variable]
const char output_file[] = "well_known_types_embed.cc";
           ^
1 warning generated.
INFO: From Linking external/com_google_protobuf/libprotobuf.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(gzip_stream.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(error_listener.o) has no symbols
ERROR: /Users/joelmuskwe/Joel/projects/examples/nx-bazel-example/libs/api/src/BUILD.bazel:5:1: SkylarkAction libs/api/src/car.d.ts failed (Exit 1)
/bin/sh: node: command not found

/private/var/tmp/_bazel_joelmuskwe/90655fb78925987361cad0d120fb1d9a/external/protobufs_compiletime_deps/node_modules/protobufjs/cli/pbts.js:126
                var err = Error("code " + code);
                          ^
Error: code 127
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_joelmuskwe/90655fb78925987361cad0d120fb1d9a/external/protobufs_compiletime_deps/node_modules/protobufjs/cli/pbts.js:126:27)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
INFO: Elapsed time: 644.333s, Critical Path: 68.93s
FAILED: Build did NOT complete successfully

**Comment by vikikamath** [comment]
I am getting the same error as above. The `backend` server starts up with following message:
```bash
May 23, 2018 10:14:40 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
May 24, 2018 2:14:52 AM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
May 24, 2018 2:15:01 AM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@localhost:8080
May 24, 2018 2:15:01 AM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:8080/
May 24, 2018 2:15:01 AM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:8080/_ah/admin
May 23, 2018 10:15:01 PM com.google.appengine.tools.development.DevAppServerImpldoStart
INFO: Dev App Server is now running
```

However the `//apps/car-list/src:devserver` fails with error as described above.
